### ISSUE TITLE
ydiff 1.4.1 PyPI source tarball is missing tests (while 1.3 did ship them)

### ISSUE THREAD

**Issue by hartwork** [ymattw/ydiff#125] opened 2024-11-17 13:59 UTC
Hi!

I'm maintaining  ydiff for Gentoo Linux and during the bump from 1.3 to 1.4.1 I became aware that https://files.pythonhosted.org/packages/cc/c0/82cb70f5e1042ec7989288e82ba43dde6809d65a31b5da81912b8c3456a1/ydiff-1.4.1.tar.gz is not containing the test suite which Gentoo packaging makes use of, so that I'll need to resort to a GitHub archive or wait for 1.4.2 with tests. I'll go with former, and want to be sure you know. Was there a conscious decision to no longer ship the tests with source tarballs?

Best, Sebastian

**Comment by ymattw** [comment] 2024-11-17 15:37
Hi! I am not aware of how ydiff is packaged for systems other than PyPI. End users should not care about the tests so I stooped shipping them starting version 1.4.

I still think it is the right behavior to not ship with tests.  Would you mind pointing me to the Gentoo packaging system? I want to understand it before proposing a solution. Thank you.

**Comment by hartwork** [comment] 2024-11-17 15:52
@ymattw the package is at https://github.com/gentoo/gentoo/commit/b5825a6fd4ac9db169b96c8eb6720218f1bb756b . To be fair, the `RESTRICT="test"` there is present for a while already and that restricts actual execution of those tests, I had another look why but found no quick answer, it seems to predate the conversion from CVS to Git… 
Some distros give users the option to run the upstream test suite for selected packages and Gentoo is one of them. Hoembrew is another but for ydiff they opted for a simple smoke tests instead apparently: https://github.com/Homebrew/homebrew-core/blob/658b2b3886f547d6b55b352bf9d5f4df7e392be1/Formula/y/ydiff.rb
I don't have strong feelings about a choice either way, but wanted to be sure you knew about this.

**Comment by ymattw** [comment] 2024-11-17 17:22
@hartwork I think your solution of referring to the GitHub archives of tagged versions is the right way to go. I am closing this issue as intended behavior. Thank you!

**Comment by AloisMahdal** [comment] 2024-12-13 11:03
I'm sorry if I'm necro-threading but..

Would you consider changing your mind, @ymattw?

I'm a package maintainer for few packages in Fedora including ydiff and I've also been involved in packaging for Red Hat, ie. I'm pretty familiar with that packaging system (and also with Debian's, which is pretty much the same thing, in things related to this discussion).

As far as I can see, it is pretty much standard to ship *with* tests.  You are right that the final user only cares about the *final* product, but the user of the app is not the same audience as user of the source code tarball; the person responsible for building & installing the app is normally also interested in testing it.  (Regardless of whether that is further automated and encansu by DEB or RPM.)

For both packaging systems I  know, the workflow is similar:
 1. download tarball,
 2. unpack it,
 3. build it (also relevant for Python packages, even though technically most of them don't require "build" in the traditional sense, ie. no ELF is really produced),
 4. run any embedded tests
 5. install it in a sandbox
 6. through meta-data, decide which files (as installed in the sandbox) are part of the package
 7. produce the final package by collecting the files as they are in the sandbox
 8. collect extra meta-data (checksums, etc.)
 9. clean up

Step 4 is always encouraged, as long as it's possible (and practical, ie. tests don't run for too long or have unacceptable requirements, etc.).

I admit I haven't been running the tests with the current Fedora package (perhaps I missed it earlier or could not make themo work---can't remember now TBH).  Seeing this ticket I realized that since there are tests then I should definitely try running them.

I don't know about Gentoo's packaging system but I assume that in the end it boils down to the same since all the motivations are actually agnostic about distros/packaging systems (and would actually apply even for manual installation).

**Comment by AloisMahdal** [comment] 2024-12-13 11:16
>  1. download tarball,
>  2. unpack it,
>  3. build it [...]

For the sake of completeness, I should have also included extra step between 2 and 3, which is to apply any "own" distribution-specific patches.  From distro POV it's critical to have this step, although it's not really relevant here :-).  (Also the step is a no-op for packages which build & work out of the box, which includes ydiff.)

**Comment by ymattw** [comment] 2024-12-15 11:48
Hi @AloisMahdal, I still think the PyPI release should not contain tests
because ydiff is an executable tool rather than a python package, the releases
are not "source" archives.

When released to PyPI, the tests were already done as part of the release
process. If other downstream packaging systems cannot trust the process and
have to run the tests again, then they should check out the "source" tree from
GitHub instead of from PyPI, and follow the procedure of running tests from
source tree including setting up the development dependencies (ydiff
integration tests do not have external dependencies but the unit tests do).

An easy solution for you case would be downloading from GitHub tagged archives.
Would that work?

**Comment by hartwork** [comment] 2024-12-15 15:20
Hi @ymattw with my Gentoo Linux developer hat on I would like to add that we love ydiff — that's why we chose to be the package maintainer for it in our respective distro —, the tests are being run not out of mistrust but because the environment is slightly different to yours — in Gentoo's case it's even run on the user's box if the user opts in, not just the packagers box, so potentially very different — and it's about catching unexpected incompatibilities in the integration. So I second what @AloisMahdal wrote above also for the case of Gentoo. Thanks for sharing ydiff and earlier cdiff as software libre with the community! :pray:

**Comment by ymattw** [comment] 2024-12-16 11:50
Hi @AloisMahdal @hartwork, I am very appreciated that you guys are maintaining the package, and I am honored to see ydiff is used that way. With all respect to your effort, I took a closer look at the PyPI guide ([Build artifacts](https://packaging.python.org/en/latest/flow/#build-artifacts)), and I believe the best practice for ydiff is to ship to PyPI with both

- The source distribution (sdist), with tests, and
- The built distribution (wheel), without tests

[Pycodestyle](https://pypi.org/project/pycodestyle/#files) is an example I found. This way,  end users can still `pip install` to install the application (wheel) without tests,  and package maintainers could fetch the source tarball from PyPI with tests. Would that work for you?

**Comment by AloisMahdal** [comment] 2024-12-16 11:52
Sorry I didn't realize this was about PyPi release specifically.  I don't know enough about PyPI but it seems like in PyPI case, there is no test phase as part of the process (the package binary is simply uploaded and then downloaded by user, as is..).

So then your argument makes sense.

And indeed, the ydiff.spec I use is using github link so I'm not affectred by this.

**Comment by AloisMahdal** [comment] 2024-12-16 11:56
I haven't read your message before posting mine.

I'm perfectly fine with using the github link.

With regards to PyPI or Gentoo I don't know enough to know what's the standard.  Realizing that PyPI is actually doing things differently then it makes sense for the expectation to be different, and keeping the tarball minimal seems like good practice.

**Comment by hartwork** [comment] 2024-12-16 15:51
Hi @ymattw,

> [..] I took a closer look at the PyPI guide ([Build artifacts](https://packaging.python.org/en/latest/flow/#build-artifacts)), and I believe the best practice for ydiff is to ship to PyPI with both
> 
> * The source distribution (sdist), with tests, and
> 
> * The built distribution (wheel), without tests

sounds perfect to me :+1:

**Comment by AloisMahdal** [comment] 2024-12-16 15:53
BTW, I went ahead and already [enabled test][src] in the Fedora package spec (tests/regression.sh).

  [src]: https://src.fedoraproject.org/rpms/ydiff/c/d211992e454c9c3417f0b230e8b15ad055e2416d?branch=rawhide

**Comment by ymattw** [comment] 2024-12-16 17:04
I have made changes accordingly so next release will start upload both source tarball (for downstream packaging systems) and the built wheel (for pip install). You can continue use github tagged source tarball for now and switch later when ydiff has a new release. Thank you all for the good discussion!

**Closed by ymattw** 2024-12-16 17:04 UTC

**Comment by hartwork** [comment] 2024-12-16 17:05
@ymattw thank you! :pray:
